### ISSUE TITLE
Fedora 41. After running command ./ML4W_Hyprland_Settings-x86_64.AppImage     the app doesnt start

### ISSUE THREAD

**Issue by inexistentHeap404** [mylinuxforwork/hyprland-settings#4]
i used the curl way of  installing from the readme. Installation gave no errors. the .AppImage was also present in ~/apps but upon running the app doesnt show up. Did i make a mistake by installing it for Fedora 41?

**Comment by mylinuxforwork** [comment]
Can you make sure that all dependencies are installed? https://github.com/mylinuxforwork/hyprland-settings?tab=readme-ov-file#dependencies
And start the appimage directly and share error messages.

**Comment by inexistentHeap404** [comment]
I think the config file creation doesn't happen, I don't get ant errors during the installation. The below message makes it clear that the installation had completed without any error (or atleast I guess)
```
python: /usr/bin/idle exists in filesystem
python: /usr/bin/idle3 exists in filesystem
python: /usr/bin/pydoc exists in filesystem
python: /usr/bin/pydoc3 exists in filesystem
python: /usr/bin/python exists in filesystem
python: /usr/bin/python-config exists in filesystem
python: /usr/bin/python3 exists in filesystem
python: /usr/bin/python3-config exists in filesystem
python: /usr/share/man/man1/python.1.gz exists in filesystem
python: /usr/share/man/man1/python3.1.gz exists in filesystem
Errors occurred, no packages were upgraded.

:: Installation started
:: Desktop file and icon installed successfully in ~/.local/share/applications

DONE!
Please add the following command to your hyprland.conf of you want to restore the changes after logging in.
exec-once = ~/.config/ml4w-hyprland-settings/hyprctl.sh

You can start the app from your application launcher...
```
but when I try to get into the directory ```~/.config/ml4w-hyprland-settings/hyprctl.sh``` the parent of ```hyprctl.sh``` does not exist in ```.config```.

**Comment by inexistentHeap404** [comment]
update  -  re-installation helps.
